[2021-12-14T13:57:54.143927+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/config/routes/dev/web_profiler.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/vendor/symfony/config/Resource/FileResource.php","line":62,"trace":[{"file":"/var/www/symfony/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":44,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-12-14T13:57:59.092449+00:00] request.INFO: Matched route "list". {"route":"list","route_parameters":{"_route":"list","_controller":"App\\Controller\\ConcertController::list","name":"hello"},"request_uri":"http://symfony.localhost/concert/hello","method":"GET"} []
[2021-12-14T13:57:59.147726+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-14T13:57:59.633608+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "concert/list.html.twig" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"concert/list.html.twig\" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form). at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2021-12-14T13:58:00.918747+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-14T13:58:00.931986+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-14T13:58:49.108182+00:00] request.INFO: Matched route "list". {"route":"list","route_parameters":{"_route":"list","_controller":"App\\Controller\\ConcertController::list","name":"hello"},"request_uri":"http://symfony.localhost/concert/hello","method":"GET"} []
[2021-12-14T13:58:49.222678+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-14T13:58:50.243472+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-14T13:58:50.737187+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b0673f"},"request_uri":"http://symfony.localhost/_wdt/b0673f","method":"GET"} []
[2021-12-14T13:58:51.083251+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b0673f"},"request_uri":"http://symfony.localhost/_wdt/b0673f","method":"GET"} []
[2021-12-14T13:59:00.412032+00:00] request.INFO: Matched route "list". {"route":"list","route_parameters":{"_route":"list","_controller":"App\\Controller\\ConcertController::list","name":"hello"},"request_uri":"http://symfony.localhost/concert/hello","method":"GET"} []
[2021-12-14T13:59:00.420055+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-12-14T13:59:00.515662+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:91)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /var/www/symfony/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2021-12-14T13:59:00.734714+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"46151f"},"request_uri":"http://symfony.localhost/_wdt/46151f","method":"GET"} []
[2021-12-14T13:59:01.005554+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"46151f"},"request_uri":"http://symfony.localhost/_wdt/46151f","method":"GET"} []
[2021-12-14T14:31:51.048457+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.en.xlf {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Users/aka/Symfony/docker-symfony/symfony/vendor/symfony/config/Resource/FileResource.php","line":62,"trace":[{"file":"/Users/aka/Symfony/docker-symfony/symfony/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":44,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-12-14T14:31:51.332574+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.af.xlf [] []
[2021-12-14T14:31:51.498783+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.ar.xlf [] []
[2021-12-14T14:31:51.639041+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.az.xlf [] []
[2021-12-14T14:31:51.881359+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.be.xlf [] []
[2021-12-14T14:31:52.080412+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.bg.xlf [] []
[2021-12-14T14:31:52.180956+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.bs.xlf [] []
[2021-12-14T14:31:52.296263+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.ca.xlf [] []
[2021-12-14T14:31:52.389857+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.cs.xlf [] []
[2021-12-14T14:31:52.466625+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.cy.xlf [] []
[2021-12-14T14:31:52.500695+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.da.xlf [] []
[2021-12-14T14:31:52.599028+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.de.xlf [] []
[2021-12-14T14:31:52.661309+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.el.xlf [] []
[2021-12-14T14:31:52.754701+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.es.xlf [] []
[2021-12-14T14:31:52.867609+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.et.xlf [] []
[2021-12-14T14:31:52.970659+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.eu.xlf [] []
[2021-12-14T14:31:53.085528+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.fa.xlf [] []
[2021-12-14T14:31:53.160605+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.fi.xlf [] []
[2021-12-14T14:31:53.239143+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.fr.xlf [] []
[2021-12-14T14:31:53.350076+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.gl.xlf [] []
[2021-12-14T14:31:53.426356+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.he.xlf [] []
[2021-12-14T14:31:53.530800+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.hr.xlf [] []
[2021-12-14T14:31:53.715981+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.hu.xlf [] []
[2021-12-14T14:31:53.787252+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.hy.xlf [] []
[2021-12-14T14:31:53.856952+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.id.xlf [] []
[2021-12-14T14:31:53.931556+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.it.xlf [] []
[2021-12-14T14:31:54.011191+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.ja.xlf [] []
[2021-12-14T14:31:54.076411+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.lb.xlf [] []
[2021-12-14T14:31:54.143982+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.lt.xlf [] []
[2021-12-14T14:31:54.206527+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.lv.xlf [] []
[2021-12-14T14:31:54.274596+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.mn.xlf [] []
[2021-12-14T14:31:54.339116+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.my.xlf [] []
[2021-12-14T14:31:54.393962+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.nb.xlf [] []
[2021-12-14T14:31:54.554141+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.nl.xlf [] []
[2021-12-14T14:31:54.613119+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.nn.xlf [] []
[2021-12-14T14:31:54.738213+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.no.xlf [] []
[2021-12-14T14:31:54.867991+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.pl.xlf [] []
[2021-12-14T14:31:54.935604+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.pt.xlf [] []
[2021-12-14T14:31:55.005434+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.pt_BR.xlf [] []
[2021-12-14T14:31:55.061561+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.ro.xlf [] []
[2021-12-14T14:31:55.102153+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.ru.xlf [] []
[2021-12-14T14:31:55.143676+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.sk.xlf [] []
[2021-12-14T14:31:55.184408+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.sl.xlf [] []
[2021-12-14T14:31:55.217975+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.sq.xlf [] []
[2021-12-14T14:31:55.281252+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.sr_Cyrl.xlf [] []
[2021-12-14T14:31:55.320898+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.sr_Latn.xlf [] []
[2021-12-14T14:31:55.356298+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.sv.xlf [] []
[2021-12-14T14:31:55.397572+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.th.xlf [] []
[2021-12-14T14:31:55.445503+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.tl.xlf [] []
[2021-12-14T14:31:55.490823+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.tr.xlf [] []
[2021-12-14T14:31:55.533211+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.uk.xlf [] []
[2021-12-14T14:31:55.571680+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.uz.xlf [] []
[2021-12-14T14:31:55.604098+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.vi.xlf [] []
[2021-12-14T14:31:55.638372+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.zh_CN.xlf [] []
[2021-12-14T14:31:55.677372+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/aka/Symfony/Symfony4.4-Docker/symfonyNEw/vendor/symfony/validator/Resources/translations/validators.zh_TW.xlf [] []
[2021-12-14T14:31:55.829890+00:00] php.DEBUG: Warning: filemtime(): stat failed for /var/www/symfony/config/routes/dev/web_profiler.yaml [] []
[2021-12-14T14:31:56.122188+00:00] php.DEBUG: Warning: filemtime(): stat failed for /var/www/symfony/config/routes/dev/web_profiler.yaml [] []
[2021-12-14T14:35:30.955787+00:00] console.CRITICAL: Error thrown while running command "'doctrine:database:update'". Message: "Command "doctrine:database:update" is not defined.  Did you mean one of these?     doctrine:database:create     doctrine:database:drop     doctrine:schema:update" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"doctrine:database:update\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:schema:update at /Users/aka/Symfony/docker-symfony/symfony/vendor/symfony/console/Application.php:709)","command":"'doctrine:database:update'","message":"Command \"doctrine:database:update\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:schema:update"} []
[2021-12-14T14:35:38.382354+00:00] doctrine.DEBUG: SELECT DATABASE() [] []
[2021-12-14T14:35:38.416023+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-12-14T14:35:38.421651+00:00] doctrine.DEBUG: SELECT DATABASE() [] []
[2021-12-14T14:35:38.444233+00:00] console.DEBUG: Command "doctrine:schema:update" exited with code "1" {"command":"doctrine:schema:update","code":1} []
[2021-12-14T14:35:46.066400+00:00] doctrine.DEBUG: SELECT DATABASE() [] []
[2021-12-14T14:35:46.078570+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-12-14T14:35:46.083851+00:00] doctrine.DEBUG: SELECT DATABASE() [] []
[2021-12-14T14:35:46.090128+00:00] doctrine.DEBUG: SELECT DATABASE() [] []
[2021-12-14T14:35:46.092429+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-12-14T14:35:46.095725+00:00] doctrine.DEBUG: SELECT DATABASE() [] []
[2021-12-14T14:35:46.097838+00:00] doctrine.DEBUG: CREATE TABLE concert (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
